# .travis.yml
dist: precise

language: php

php:
  - 7.3

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - php artisan key:generate

script:
  - vendor/bin/phpunit
